update pipe

diff --git a/.github/workflows/sf-validate-pr.yml b/.github/workflows/sf-validate-pr.yml
--- a/.github/workflows/sf-validate-pr.yml
+++ b/.github/workflows/sf-validate-pr.yml
@@ -27,7 +27,7 @@ jobs:
         with:
           fetch-depth: 0
 
-          
+
       - name: Install Dependencies
         uses: ./.github/actions/install-dependencies
 
@@ -57,22 +57,22 @@ jobs:
       #   id: pmd-scan
       #   uses: ./.github/actions/sf-code-scanner
 
-      - name: Upload SARIF file
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: "changed-sources/apexScanResults.sarif"
+      # - name: Upload SARIF file
+      #   uses: github/codeql-action/upload-sarif@v3
+      #   with:
+      #     sarif_file: "changed-sources/apexScanResults.sarif"
 
-      - name: Check PMD Results
-        shell: bash
-        run: |
-          if [ $SCAN_EXIT_CODE -ne 0 ]; then
-            echo "PMD Scan failed with exit code $SCAN_EXIT_CODE"
-            exit 1
-          else
-            echo "Scan completed successfully"
-          fi
-        env:
-          SCAN_EXIT_CODE: ${{ steps.pmd-scan.outputs.scan-exit-code }}
+      # - name: Check PMD Results
+      #   shell: bash
+      #   run: |
+      #     if [ $SCAN_EXIT_CODE -ne 0 ]; then
+      #       echo "PMD Scan failed with exit code $SCAN_EXIT_CODE"
+      #       exit 1
+      #     else
+      #       echo "Scan completed successfully"
+      #     fi
+      #   env:
+      #     SCAN_EXIT_CODE: ${{ steps.pmd-scan.outputs.scan-exit-code }}
 
       - name: Check Only Deployment
         uses: ./.github/actions/sf-validate-delta
